-- -- Create the sequence
CREATE SEQUENCE seq_customer START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_account START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_transaction START WITH 1001 INCREMENT BY 1;
